flatpak install flathub com.google.Chrome
flatpak install flathub io.dbeaver.DBeaverCommunity
flatpak install flathub com.visualstudio.code
flatpak install flathub org.libretro.RetroArch
flatpak install flathub page.kramo.Cartridges
flatpak install flathub org.blender.Blender
flatpak install flathub com.rtosta.zapzap
flatpak install flathub com.github.libresprite.LibreSprite
flatpak install flathub org.godotengine.Godot
flatpak install flathub com.github.sdv43.whaler
flatpak install flathub com.anydesk.Anydesk